### PR TITLE
Fix the Why LuckPerms page

### PR DESCRIPTION
**Pull request by Unix101**
This PR fixes a few of Why-LuckPerms.md's images and odd spacings.

### CODE REVIEW

**Comment by lucko** [comment]
Hey, thanks for the PR - I would really prefer if we keep using Imgur and Gfycat for the embedded images though please!

**Comment by Unix101** [comment]
Sure, if I can get those working correctly I'll redo it with that.

**Comment by Unix101** [comment]
Hopefully, it's fixed now! Sorry about the wait and if anything's messed up just comment!

**Comment by lucko** [comment]
Sorry to be a massive pain, but it's occurred to me that it would probably be sensible to just link to the demo pages...

(we didn't have demos when this wiki page was first written)

**Comment by Unix101** [comment]
Something like this?

**Comment by lucko** [comment]
Great, thanks!

**Pull request merged**
