### PR TITLE
v5

### PR DESCRIPTION
**Pull request by Tobi406**
> Changes needed to made for the v5 release of LuckPerms.

## To-Do list
- [x] Rename package (me.lucko.luckperms -> net.luckperms)
- [x] Change domain
- [x] Remove default assignements
   - [ ] Add if they come back with an extension
- [ ] Update images
- [ ] Add v5 changes to the changelog

### CODE REVIEW

**Comment by Andre601** [comment]
Maybe add to the to-do to actually add the changes of v5 to the changelog once Luck has committed everything and the API is ready for release.

**Comment by Tobi406** [comment]
> Maybe add to the to-do to actually add the changes of v5 to the changelog once Luck has committed everything and the API is ready for release.

Done

**Comment by Turbotailz** [comment]
Web editor ;)

**Comment by Tobi406** [comment]
Still some work to do. 

Is the wording of https://github.com/LuckPerms/wiki/pull/15/commits/96d3da62abd701b2e8a900de1c0cf89e03537a46 ok?

**Pull request closed without merging**
