### PR TITLE
Correct wrong information about addtemp/settemp

### LINKED ISSUE #1813: 1M is one minute and not one month
I confirmed while trying to set up temporary parents that 1M is one minute* and not one month* as listed in the documentation. Likely due to a lower casing of arguments at some point. Tested for both parent addtemp and permission settemp.

LuckPerms version 4.4.1 running on Paper 226.

Edit: Switcheroo'd

### PR DESCRIPTION
**Pull request by Andre601**
Fixes https://github.com/lucko/LuckPerms/issues/1813

### CODE REVIEW

**Comment by BrainStone** [comment]
Are you sure that hasn't been changed in v5?

**Comment by BrainStone** [comment]
Nevermind.

I'd suggest you add a little section with all the time units and remove the wrong link

Valid units:

```
s  -> seconds
m  -> minutes
h  -> hours
d  -> days
w  -> weeks
mo -> months
y  -> years
```

**Comment by Andre601** [comment]
what "wrong link"?

**Comment by BrainStone** [comment]
The one to SimpleDateFormat and that you already removed.

**Pull request merged**
