### PR TITLE
Add answer to common arg. based cmd. perms question

### PR DESCRIPTION
**Pull request by Laarryy**
Let me know if this can be improved. So far the simplest way I know of to do this.

### CODE REVIEW

**Comment by Laarryy** [comment]
For some reason my previous, (already implemented) commits tagged along. Will update to match master next time, sorry.

**Comment by Andre601** [comment]
I think it would be better suited to add this as an example to the [argument based command permission page](https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions) because it seems like a too specifc question imo and not really suited for FAQ.

**Comment by Laarryy** [comment]
It's added to the end of the arg. based command perms page, not the FAQ

**Comment by Andre601** [comment]
I see. It's kind of like a FAQ question in terms of title, rather than how the site itself is styled.
I suggest changing the text to `Promote  other players to ranks below but not higher or equal to their own role` or something like that, to match the general syntax/*style* of the other parts.

**Comment by Laarryy** [comment]
Good idea. It's added.

**Pull request merged**
