### PR TITLE
Add weights wiki

### PR DESCRIPTION
**Pull request by Laarryy**
Added a page to explain weights

### CODE REVIEW

**Comment by lucko** [comment]
This is great! Thank you :tada:

**Comment by Andre601** [comment]
@lucko You should've waited with the merge of this, as I had questions, but also saw some issues.

@Laarryy Why do you have an empty line between List entries? From what I remember does none of the other pages have this and it just looks silly.
Next did you use complete URLs to wiki pages and not relative links, meaning you have to update this now, so that it will be ready once the wiki moves.

You also messed up the URLs themself.

**Comment by Turbotailz** [comment]
> Next did you use complete URLs to wiki pages and not relative links

It's fine, that can be fixed in my PR.

**Comment by Andre601** [comment]
I'm already on fixing it

**Comment by lucko** [comment]
@Andre601 I saw no issues with this PR so merged it. Despite what you may otherwise think, I don't need to wait for your explicit approval 😛 

If you have improvements or other ideas to suggest, feel free to do so in another PR. There's no need to criticise someone else's contribution.

**Comment by Andre601** [comment]
> @Andre601 I saw no issues with this PR so merged it. Despite what you may otherwise think, I don't need to wait for your explicit approval 😛 
> 
> If you have improvements or other ideas to suggest, feel free to do so in another PR. There's no need to criticise someone else's contribution.

So you did see the obviously broken links (`[text]([text](link))`) and thought it's fine?

Providing critic and maybe look for feedback and opinions of others is a key part of contributions.
And it's not like you did wait weeks before merging or closing PRs before...

I'm sorry, but this response from you is very unwelcoming. New contributors will feel like they shouldn't contribute in the first place.

I get more and more the feel that I'm no longer welcome here.
PRs I make stay open for x days while others get merged nearly instant (My Edito PR sure wouldn't have been merged until now if Larry didn't make one himself) and when I try to contribute stuff is it often altered or denied for "reasons".
It's almost like you have something against me (say what you will, I feel like that).
I'm really close to leave this project and community because I feel more and more unwelcome.

**Comment by lucko** [comment]
> So you did see the obviously broken links `([text]([text](link)))` and thought it's fine?

Nope didn't notice those!

> I'm sorry, but this response from you is very unwelcoming. New contributors will feel like they shouldn't contribute in the first place.

Oh yes, this message was highly unwelcoming... 

> This is great! Thank you 🎉

> I get more and more the feel that I'm no longer welcome here.
PRs I make stay open for x days while others get merged nearly instant

Purely coincidental. Of course you're welcome, so long as you're nice to others & avoid needlessly criticising other people's contributions, as I said before:

> If you have improvements or other ideas to suggest, feel free to do so in another PR. There's no need to criticise someone else's contribution.

It's nothing personal, and I'm sorry if you feel unwelcome. Wasn't my intention.

**Pull request merged**
