### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by Andre601**
Weight.md used broken links and the _sidenav.md also used absolute URLs instead of relative ones.

### CODE REVIEW

**Comment by lucko** [comment]
The conversion to relative links is already being handled here #57 - no need to duplicate.

**Comment by Andre601** [comment]
This PR still contains changes like making list entries match the style of existing ones (`- zext` -> `* text`)

**Comment by lucko** [comment]
Sure ok, change it to just fix that then & the broken links. The change from absolute --> relative can be handled later all in one go.

**Comment by Andre601** [comment]
No thanks. I no longr feel welcome here after this. (See my updated comment on the other PR)

**Comment by Andre601** [comment]
Alright.
I still changed the URLs as they where wrong (`[text]([text](url))`) and added a URL to Installation on the _Sidenav.md for consistency (Was missing there)

On a different note would I consider to alter the command page names, as I had issues checking out the text locally and the error always pointed to `Command-Usage:-General.md`

**Comment by lucko** [comment]
Great, thank you!

**Pull request merged**
