### PR TITLE
Remove Default Assignements section

### PR DESCRIPTION
**Pull request by Tobi406**
Removes the default assignments section.

### CODE REVIEW

**Comment by BrainStone** [comment]
Why?

They still exist.

**Comment by Tobi406** [comment]
They still exist, but aren't in by default. I thaught about making a link from the section to the "Upgrading from v4 to v5" page. Or should the documentation maybe be moved to the extension's repo?

**Comment by BrainStone** [comment]
I'd leave it here and explicitly point out that you need the extension.

**Comment by Tobi406** [comment]
Maybe this looks better?

**Comment by lucko** [comment]
Looks good to me!

**Pull request merged**
