### PR TITLE
Fix the arg based perms promotion guide to include spigot

### PR DESCRIPTION
**Pull request by Laarryy**
Only included Sponge before, with Brain's help I've reworked it to universally work for both Sponge and Spigot, and it makes sense now.

### CODE REVIEW

**Comment by Andre601** [comment]
You should perhaps base this on the PR #54 to have relative links for the upcoming transition/integration towards the new online wiki.
Also, this has unsolved conflicts.

**Comment by Laarryy** [comment]
@Andre601 I just modified the table at the bottom, don't see where I included or excluded any relevant relative links, as that's not what I was trying to do. 

Thanks for the heads up on the conflicts, resolved them :)

**Comment by Andre601** [comment]
The very top of the file has a absolute link (https://github.com/...) rather than a relative link.

It shouldn't matter that much, if this PR is merged before 54, but when the oposite happens would this need to be rebased.

**Comment by lucko** [comment]
> but when the oposite happens would this need to be rebased

Git is clever ;)

**Comment by lucko** [comment]
Thanks Larry!

**Comment by Andre601** [comment]
> Git is clever ;)

Due to knowing git from personal experience do I highly doubt that.

**Pull request merged**
