### PR TITLE
Added RabbitMQ configuration and updated table

### PR DESCRIPTION
**Pull request by BomBardyGamer**
Does what it says in the title, not much more to say.

### CODE REVIEW

**Comment by BomBardyGamer** [comment]
I reformatted the table there so everything lines up, just looks a bit better I think

**Comment by lucko** [comment]
Looks good, but could you revert the changes to the table formatting, and just insert the RabbitMQ line under the Redis one.

**Comment by BomBardyGamer** [comment]
Yeah I was thinking of doing that, will do

**Comment by lucko** [comment]
If you check the diff, the table formatting is still different :p

**Comment by BomBardyGamer** [comment]
Yeah I thought it was better because then everything is aligned. Need that reverted?

**Comment by lucko** [comment]
Ah it's fine, don't worry :)

Thanks!

**Pull request merged**
